("SME FP64 outer product" ("sme" "sme outer product")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (ZAda 3)))
("SME Int16 outer product" ("sme" "sme outer product")
  ((_ 2) (_ 5) (u0 1) (_ 2) (u1 1) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (ZAda 3)))
("SME FP32 outer product" ("sme" "sme fp outer product")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 1) (ZAda 2)))
("SME FP64 widening outer product" ("sme" "sme fp outer product")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 1) (ZAda 2)))
("SME2 32-bit binary outer product" ("sme" "sme2 outer product - misc")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 1) (ZAda 2)))
("SME2 FP16 non-widening outer product" ("sme" "sme2 outer product - misc")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 2) (ZAda 1)))
("SME2 BP16 non-widening outer product" ("sme" "sme2 outer product - misc")
  ((_ 2) (_ 9) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 2) (ZAda 1)))
("SME2 Int16 two-way outer product" ("sme" "sme integer outer product - 32 bit")
  ((_ 2) (_ 5) (u0 1) (_ 3) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 1) (ZAda 2)))
("SME Int8 outer product" ("sme" "sme integer outer product - 32 bit")
  ((_ 2) (_ 5) (u0 1) (_ 2) (u1 1) (Zm 5) (Pm 3) (Pn 3) (Zn 5) (S 1) (_ 1) (_ 1) (ZAda 2)))
("SME2 multi-vec contiguous load (scalar plus scalar, two registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 4) (N 1)))
("SME2 multi-vec contiguous load (scalar plus scalar, four registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 3) (_ 1) (N 1)))
("SME2 multi-vec contiguous store (scalar plus scalar, two registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 4) (N 1)))
("SME2 multi-vec contiguous store (scalar plus scalar, four registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 3) (_ 1) (N 1)))
("SME2 multi-vec contiguous load (scalar plus immediate, two registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 4) (N 1)))
("SME2 multi-vec contiguous load (scalar plus immediate, four registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 3) (_ 1) (N 1)))
("SME2 multi-vec contiguous store (scalar plus immediate, two registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 4) (N 1)))
("SME2 multi-vec contiguous store (scalar plus immediate, four registers)" ("sme" "sme2 multi-vector" "contiguous")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zt 3) (_ 1) (N 1)))
("SME2 multi-vec non-contiguous load (scalar plus scalar, two registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (Ztl 3)))
("SME2 multi-vec non-contiguous load (scalar plus scalar, four registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (_ 1) (Ztl 2)))
("SME2 multi-vec non-contiguous store (scalar plus scalar, two registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (Ztl 3)))
("SME2 multi-vec non-contiguous store (scalar plus scalar, four registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 11) (Rm 5) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (_ 1) (Ztl 2)))
("SME2 multi-vec non-contiguous load (scalar plus immediate, two registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (Ztl 3)))
("SME2 multi-vec non-contiguous load (scalar plus immediate, four registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (_ 1) (Ztl 2)))
("SME2 multi-vec non-contiguous store (scalar plus immediate, two registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (Ztl 3)))
("SME2 multi-vec non-contiguous store (scalar plus immediate, four registers)" ("sme" "sme2 multi-vector" "strided")
  ((_ 12) (imm4 4) (_ 1) (msz 2) (PNg 3) (Rn 5) (Zth 1) (N 1) (_ 1) (Ztl 2)))
("SME move vector to array" ("sme" "sme move into array")
  ((_ 8) (size 2) (_ 5) (Q 1) (V 1) (Rs 2) (Pg 3) (Zn 5) (_ 1) (opc 4)))
("SME2 move vector to tile, two registers" ("sme" "sme move into array")
  ((_ 2) (_ 6) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (Zn 4) (_ 2) (_ 1) (opc 3)))
("SME2 move vector to tile, four registers" ("sme" "sme move into array")
  ((_ 2) (_ 6) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (Zn 3) (_ 3) (_ 1) (opc 3)))
("SME zeroing move array to vector" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 5) (Q 1) (V 1) (Rs 2) (_ 3) (_ 1) (opc 4) (Zd 5)))
("SME move array to vector" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 5) (Q 1) (V 1) (Rs 2) (Pg 3) (_ 1) (opc 4) (Zd 5)))
("SME2 move tile to vector, two registers" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (_ 2) (opc 3) (Zd 4) (_ 1)))
("SME2 zeroing move tile to vector, two registers" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (_ 2) (opc 3) (Zd 4) (_ 1)))
("SME2 move tile to vector, four registers" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (_ 2) (opc 3) (Zd 3) (_ 2)))
("SME2 zeroing move tile to vector, four registers" ("sme" "sme move from array")
  ((_ 8) (size 2) (_ 6) (V 1) (Rs 2) (_ 3) (_ 2) (opc 3) (Zd 3) (_ 2)))
("SME add vector to array" ("sme" "sme add vector to array")
  ((_ 2) (_ 7) (op 1) (_ 5) (V 1) (Pm 3) (Pn 3) (Zn 5) (_ 1) (_ 1) (opc2 3)))
("SME2 Multiple vectors zero array" ("sme" "sme zero" "sme2 multiple zero")
  ((_ 2) (_ 12) (opc 3) (Rv 2) (_ 3) (_ 6) (_ 1) (opc2 3)))
("SME2 zero lookup table" ("sme" "sme2 zero lookup table")
  ((_ 22) (_ 6) (opc 4)))
("SME2 move from lookup table" ("sme" "sme2 move lookup table")
  ((_ 17) (imm3 3) (opc 7) (Rt 5)))
("SME2 move into lookup table" ("sme" "sme2 move lookup table")
  ((_ 17) (imm3 3) (opc 7) (Rt 5)))
